cat <<static
## Installation
The projects in this repo use the [Verint-XM iOS SDK](https://github.com/foreseecode/VerintXM-SP/), which is loaded using SPM. (For examples using Cocoapods to load the SDK, checkout the \`deprecated/cocoapods\` branch.)

## Projects
All projects can be found in \`VerintSamples.xcworkspace\`. Instructions for running each app can be found below. (This text is autogenerated from the \`README.md\` files within each project.)

static

for file in */
do
    if [ -d $file ]; then
        if [ "$(basename "$file")" = "fastlane" ]; then
          # ignoring fastlane dir
          continue
        fi;
        if [ -e $file/README.md ]
        then
            echo "##" `basename "$file"`
            cat "$file/README.md"
            echo ""
        fi;
    fi;
done;


cat <<static2
---
### A note about this README
This document is autogenerated from each sub-project's individual README.md file and should not be manually edited. To regenerate it, run:

    ./generate_readme.sh > README.md
static2
