cat <<static
## Installation
This project requires [CocoaPods](https://cocoapods.org/). After cloning, run:

    pod install

## Projects
All projects can be found in \`ForeSeeSamples.xcworkspace\`. Instructions for running each app can be found below. (This text is autogenerated from the \`README\` files within each project.)
static

for file in */
do
    if [ -d $file ]; then
        if [ -e $file/README ]
        then
            echo "##" `basename "$file"`
            cat "$file/README"
        fi;
        echo ""
    fi;
done;


cat <<static2
---
### A note about this README
This document is autogenerated from each sub-project's individual README file and should not be manually edited. To regenerate it, run:

    ./generate_readme.sh > README.md
static2
