# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'MyFrameworkCocoapodCheck' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'ForeSee', '6.0.3'

  # Pods for MyFrameworkCocoapodCheck

  target 'MyFrameworkCocoapodCheckTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MyFrameworkCocoapodCheckUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end
